### ISSUE TITLE
Filter 'webalize' doesn't exist

### ISSUE THREAD

**Issue by sjardim** [nette/latte#142]
Can't find 'webalize' in filters, although it's present in the documentation.

**Comment by TomasVotruba** [comment]
Could you link the documentation please?

**Comment by sjardim** [comment]
Sure, there you go: [https://latte.nette.org/en/filters#toc-webalize](https://latte.nette.org/en/filters#toc-webalize)

**Comment by JanTvrdik** [comment]
@sjardim That's because `webalize` filter is provided by [latte bridge in nette/application](https://github.com/nette/application/blob/7b07c4e3aa150fdea0b7765a7223bca621136689/src/Bridges/ApplicationLatte/TemplateFactory.php#L74-L76).

To add this filter manually you need to require `nette/utils` a call 

~~~php
$latte->addFilter('webalize', 'Nette\Utils\Strings::webalize');
~~~

**Comment by sjardim** [comment]
Thanks for clarifying it, @JanTvrdik !
I'm using Latte outside Nette, in a [ProcessWire project](github.com/rolandtoth/TemplateLatteReplace), so that's why it didn't work! :)

**Comment by dg** [comment]
I agree that documentation should be updated only.

**Comment by TomasVotruba** [comment]
@dg Just remove the line in https://latte.nette.org/en/filters#toc-webalize?

**Comment by dg** [comment]
Closed by https://github.com/nette/web-content/commit/b3bcbf1bc69f286c7346d5a9020a6a05ccf2808d

**Comment by TomasVotruba** [comment]
Wow, awesome update! Thanks
