### ISSUE TITLE
Support typehints in {var}, {default} and {define} macros

### ISSUE THREAD

**Issue by JanTvrdik** [nette/latte#151]
Based on discussion with @matej21 we suggest extending syntax of `{var}`, `{default}` and `{define}` macros to support defining types. The following syntax is proposed:

~~~
{var int $number = 123} or without setting value {var int $number}
{var int $number, string|true $union}  multiple variables are allowed
{default int $number = 123}
{define myBlock int $a, ?Post $b} ... {/}
~~~

The code should be compiled in PHP 7 to native `assert()` call, e.g. to sth like

~~~php
assert(isset($number) && is_int($number), '$number must exist and be integer');
assert(isset($union) && (is_string($union) || $union === TRUE), '$union must exist and be string or TRUE')
~~~

Compiling to native `assert` allows for further static analysis by tools such as phpstan by @ondrejmirtes.

---

The type information may also be used by Latte plugin to provide code completion.

**Comment by ondrejmirtes** [comment]
Nice, but I don't quite like mixing two purposes in one macro - assigning new variables and defining type for variables passed from the presenter or TemplateFactory.

**Comment by JanTvrdik** [comment]
@ondrejmirtes Defining both type and value in one line is what pretty much every programming language does. I don't see the problem.

**Comment by ondrejmirtes** [comment]
The issue is that Java doesn't do this:

`IFoo $foo; // this is a method argument`
`IFoo $foo = new Foo(); // this is a new object created here`

My problem is that you have to read quite a lot of the line to realize whether this is a parameter passed from the above scope (including template, presenter, control etc.) or a new value created inside the template:

`{var int $number} // this is a template argument`
`{var int $number = 123} // this is a new value created here`

**Comment by ondrejmirtes** [comment]
So a new macro like `{type}` or `{arg}` would be better imho.

**Comment by hrach** [comment]
I don't like the proposed semantic either. Generally, value of new assignmend value can be derived, if the correctt,types are assigned at the beginning. Like $presenter, component and other variables passed to the template.

**Comment by ondrejmirtes** [comment]
Yep, basic type inference, which is quite easy.

**Comment by JanTvrdik** [comment]
Could you elaborate on what you mean by type inference in this situation?

If you mean that `{var $n = 123}` would be equal to `{type int $n} {$var $n = 123}` then it seems both pointless and BC break.

**Comment by ondrejmirtes** [comment]
My point is that with `{var $n = 123}`, I don't need any type specification nor asserting it after assigning. Because I can clearly see that `$n` is an integer because `123` is integer literal. This is a solved problem because I already analyze type inference in PHPStan for general PHP code. You can see it in [`Scope::getType()`](https://github.com/phpstan/phpstan/blob/master/src/Analyser/Scope.php#L315) and combining types in NodeScopeResolver for cases like this:

```
$foo = 123; // integer
if (doFoo()) {
    $foo = null;
}

// $foo is int|null here
```
