### ISSUE TITLE
Cached templates that no longer exist

### ISSUE THREAD

**Issue by rkocman** [nette/latte#186]
Version: 2.4.8

### Bug Description
I am not really sure if this is a bug or a feature, but if you render some template with cache enabled and then you remove the source file, the cached version is still being used. I think that this depends on your interpretation of what it means for a cached template to be expired.

### Steps To Reproduce
1. render some template with cache enabled
2. remove the source file
3. render the same path again

### Expected Behavior
Exception 'missing template file'

### Possible Solution
The function isExpired in Latte\Loaders\FileLoader is already being called, however, it only checks the modification time of the source file and not its existence. I can use my own FileLoader that fixes this, but why this isn't somehow possible in default?

**Comment by milo** [comment]
Verified. When `source.latte` is removed and cached PHP file still exists, it is used even with `$autoRefresh` enabled.

In this case, [`FileLoader::isExpired()`](https://github.com/nette/latte/blob/c728e184820d7945d1981ae347b75b0b1156d11b/src/Latte/Loaders/FileLoader.php#L53) returns false, because `filemtime()` results to false which is always less than given timestamp.
