### ISSUE TITLE
Suggestion for ref arrays syntax in templates

### ISSUE THREAD

**Issue by guilhermeaiolfi** [nette/latte#229]
Hi,

wouldn't it be nice to use the dot notation for array just like JS does? 

We can keep the current ```{$myArr.['index']```, but allow it to be ```{$meArr.index}``` too. It would save 3 chars for every indexers ref. It makes it more clear too, instead of:

```
{$myArr["really"]["long"]["nested"]["value"]}
```
This:
```
{$myArr.really.long.nexted.value}
```

Maybe having an option to silently ignore undefined array paths would be nice too. What do you guys think?

**Comment by dg** [comment]
Quotes in Latte are optional, so you can write `{$myArr[really][long][nested][value]}`. Now dot saves only 1 char, but it will keep PHP feeling.

You can simply include variables in it: `{$myArr[really][$key]}`, which would be problematic in the case of dot syntax `{$myArr.really.$key}` because it can be understood as ``{$myArr[really] . $key}`. 

Dot is used in JS primarly for object access in JS, ie. `{$obj.prop}` would have to work too, which complicates the whole thing. In addition, there is an incompatibility, because `{$obj.prop}` means `{$obj . 'prop'}` now.
